# Generated by Django 2.1.3 on 2018-12-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronica', '0002_tiendas'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiendas',
            name='productos',
            field=models.ManyToManyField(to='electronica.Productos'),
        ),
    ]
