# Generated by Django 2.1.3 on 2018-12-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronica', '0003_tiendas_productos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiendas',
            name='productos',
        ),
        migrations.AddField(
            model_name='productos',
            name='productos',
            field=models.ManyToManyField(to='electronica.Tiendas'),
        ),
    ]
