# Generated by Django 2.1.3 on 2018-12-02 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electronica', '0005_auto_20181202_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiendas',
            name='encargado',
        ),
        migrations.RemoveField(
            model_name='tiendas',
            name='productos',
        ),
    ]
