# Generated by Django 2.1.3 on 2018-12-02 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electronica', '0006_auto_20181202_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiendas',
            name='produc',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='electronica.Productos'),
        ),
    ]
