# Generated by Django 2.1.3 on 2018-12-02 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('electronica', '0008_auto_20181202_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiendas',
            name='produc',
        ),
        migrations.AddField(
            model_name='tiendas',
            name='encargado',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tiendas',
            name='productos',
            field=models.ManyToManyField(to='electronica.Productos'),
        ),
    ]
