# Generated by Django 2.1.3 on 2018-12-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronica', '0010_auto_20181202_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiendas',
            name='productos',
        ),
        migrations.AddField(
            model_name='tiendas',
            name='productos',
            field=models.ManyToManyField(to='electronica.Productos'),
        ),
    ]
