# Generated by Django 2.1.3 on 2018-12-04 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electronica', '0012_venta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='sucursal_venta',
        ),
        migrations.AddField(
            model_name='venta',
            name='sucursal_venta',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='electronica.Tiendas'),
            preserve_default=False,
        ),
    ]
