# Generated by Django 2.1.4 on 2018-12-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronica', '0013_auto_20181203_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='imagen_productos',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
