# Generated by Django 2.1.4 on 2018-12-05 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electronica', '0014_productos_imagen_productos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='imagen_productos',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='venta',
            name='sucursal_venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electronica.Tiendas'),
        ),
    ]
